using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SmartInvoice.Invoice.Models.Pdf;

namespace SmartInvoice.Invoice.Services.Pdf
{
    public class InvoicePdfDocument : IDocument
    {
        private readonly InvoicePdfModel _model;

        public InvoicePdfDocument(InvoicePdfModel model)
        {
            _model = model;
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container
                .Page(page =>
                {
                    page.Margin(50);
                    page.Size(PageSizes.A4);
                    page.DefaultTextStyle(x => x.FontSize(10));

                    page.Header().Element(ComposeHeader);
                    page.Content().Element(ComposeContent);
                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Page ");
                        x.CurrentPageNumber();
                        x.Span(" of ");
                        x.TotalPages();
                        x.Span(" | Generated by SmartInvoice");
                    });
                });
        }

        private void ComposeHeader(QuestPDF.Infrastructure.IContainer container)
        {
            container.Row(row =>
            {
                row.RelativeItem(2).Column(column =>
                {
                    column.Item().Text("INVOICE").Bold().FontSize(24).FontColor(Colors.Blue.Darken3);
                    column.Item().Text(text =>
                    {
                        text.Span("#").SemiBold();
                        text.Span(_model.InvoiceNumber);
                    });

                    column.Spacing(10);

                    column.Item().Text("Bill From").FontSize(12).SemiBold();
                    column.Item().Text(_model.Company.Name);
                    column.Item().Text(_model.Company.Address);
                    column.Item().Text(_model.Company.CityStateZip);
                    column.Item().Text($"Phone: {_model.Company.Phone}");
                    column.Item().Text($"Email: {_model.Company.Email}");
                });

                row.RelativeItem().Column(column =>
                {
                    column.Item().PaddingBottom(20).AlignRight().Text(text =>
                    {
                        text.Span("Status: ").SemiBold();
                        text.Span(_model.Status).FontColor(_model.GetStatusColor());
                    });

                    column.Item().Border(1).Padding(10).Background(Colors.Grey.Lighten3).Column(innerColumn =>
                    {
                        innerColumn.Item().Text("Invoice Details").Bold().FontSize(12);
                        innerColumn.Item().Row(row =>
                        {
                            row.RelativeItem().Text("Issue Date:");
                            row.RelativeItem().Text(_model.GetFormattedDate(_model.IssueDate)).SemiBold();
                        });
                        innerColumn.Item().Row(row =>
                        {
                            row.RelativeItem().Text("Due Date:");
                            row.RelativeItem().Text(_model.GetFormattedDate(_model.DueDate))
                                .SemiBold()
                                .FontColor(_model.IsOverdue ? Colors.Red.Medium : Colors.Black);
                        });
                        innerColumn.Item().Row(row =>
                        {
                            row.RelativeItem().Text("Balance:");
                            row.RelativeItem().Text(_model.FormatCurrency(_model.Balance))
                                .SemiBold()
                                .FontColor(_model.IsFullyPaid ? Colors.Green.Medium : Colors.Red.Medium);
                        });
                    });
                });
            });
        }

        private void ComposeContent(QuestPDF.Infrastructure.IContainer container)
        {
            container.Column(column =>
            {
                column.Item().PaddingBottom(20).Text("Bill To").FontSize(12).SemiBold();
                column.Item().Text(_model.Customer.Name);
                column.Item().Text(_model.Customer.Email);
                if (!string.IsNullOrEmpty(_model.Customer.Company))
                    column.Item().Text(_model.Customer.Company);
                if (!string.IsNullOrEmpty(_model.Customer.Phone))
                    column.Item().Text($"Phone: {_model.Customer.Phone}");

                column.Spacing(30);

                // Invoice Items Table
                column.Item().Element(ComposeTable);

                column.Spacing(20);

                // Totals
                column.Item().AlignRight().Width(250).Column(totalsColumn =>
                {
                    totalsColumn.Item().Row(row =>
                    {
                        row.RelativeItem().Text("Subtotal:");
                        row.RelativeItem().Text(_model.FormatCurrency(_model.SubTotal)).SemiBold();
                    });
                    totalsColumn.Item().Row(row =>
                    {
                        row.RelativeItem().Text("Tax:");
                        row.RelativeItem().Text(_model.FormatCurrency(_model.TaxAmount)).SemiBold();
                    });
                    totalsColumn.Item().PaddingTop(5).BorderBottom(1).BorderColor(Colors.Grey.Medium);
                    totalsColumn.Item().Row(row =>
                    {
                        row.RelativeItem().Text("Total:").Bold().FontSize(12);
                        row.RelativeItem().Text(_model.FormatCurrency(_model.TotalAmount)).Bold().FontSize(12);
                    });
                    if (_model.Balance > 0)
                    {
                        totalsColumn.Item().PaddingTop(5).Row(row =>
                        {
                            row.RelativeItem().Text("Balance Due:").Bold().FontColor(Colors.Red.Medium);
                            row.RelativeItem().Text(_model.FormatCurrency(_model.Balance)).Bold().FontColor(Colors.Red.Medium);
                        });
                    }
                    else if (_model.IsFullyPaid)
                    {
                        totalsColumn.Item().PaddingTop(5).Row(row =>
                        {
                            row.RelativeItem().Text("Paid in Full").Bold().FontColor(Colors.Green.Medium);
                            row.RelativeItem().Text("✓").Bold().FontColor(Colors.Green.Medium).FontSize(16);
                        });
                    }
                });

                // Notes
                if (_model.HasNotes)
                {
                    column.Item().PaddingTop(30).Text("Notes").FontSize(12).SemiBold();
                    column.Item().Border(1).Padding(10).Background(Colors.Grey.Lighten3).Text(_model.Notes);
                }

                // Payments
                if (_model.HasPayments)
                {
                    column.Item().PaddingTop(30).Text("Payment History").FontSize(12).SemiBold();
                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(); // Date
                            columns.RelativeColumn(); // Method
                            columns.RelativeColumn(); // Amount
                            columns.RelativeColumn(); // Status
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Date").SemiBold();
                            header.Cell().Text("Method").SemiBold();
                            header.Cell().Text("Amount").SemiBold();
                            header.Cell().Text("Status").SemiBold();
                        });

                        foreach (var payment in _model.Payments)
                        {
                            table.Cell().Text(payment.PaymentDate.ToString("dd/MM/yyyy"));
                            table.Cell().Text(payment.Method);
                            table.Cell().Text(_model.FormatCurrency(payment.Amount));
                            table.Cell().Text(payment.Status);
                        }
                    });
                }
            });
        }

        private void ComposeTable(QuestPDF.Infrastructure.IContainer container)
        {
            container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(30); // #
                    columns.RelativeColumn(3); // Description
                    columns.ConstantColumn(80); // Quantity
                    columns.ConstantColumn(80); // Unit Price
                    columns.ConstantColumn(80); // Discount
                    columns.ConstantColumn(100); // Total
                });

                table.Header(header =>
                {
                    header.Cell().Text("#").SemiBold();
                    header.Cell().Text("Description").SemiBold();
                    header.Cell().Text("Quantity").SemiBold();
                    header.Cell().Text("Unit Price").SemiBold();
                    header.Cell().Text("Discount").SemiBold();
                    header.Cell().Text("Total").SemiBold();

                    header.Cell().ColumnSpan(6).PaddingTop(5).BorderBottom(1).BorderColor(Colors.Black);
                });

                for (int i = 0; i < _model.Items.Count; i++)
                {
                    var item = _model.Items[i];

                    table.Cell().Text((i + 1).ToString());
                    table.Cell().Text(item.Description);
                    table.Cell().Text($"{item.Quantity} {item.UnitType}");
                    table.Cell().Text(_model.FormatCurrency(item.UnitPrice));
                    table.Cell().Text(item.DiscountPercentage > 0 ? $"{item.DiscountPercentage}%" : "-");
                    table.Cell().Text(_model.FormatCurrency(item.Total));

                    if (i < _model.Items.Count - 1)
                    {
                        table.Cell().ColumnSpan(6).PaddingTop(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
                    }
                }
            });
        }
    }
}